# Generated by Django 3.2.9 on 2021-11-10 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('reference', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('sw_contract', models.BooleanField(default=False)),
                ('hw_contract', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('subset', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='priority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='low', max_length=50)),
                ('color', models.CharField(default='green', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotline.department')),
            ],
        ),
        migrations.CreateModel(
            name='status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='pending', max_length=50)),
                ('color', models.CharField(default='red', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotline.department')),
            ],
        ),
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField()),
                ('duration', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_number', models.IntegerField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotline.customer')),
                ('priority_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotline.priority')),
                ('products', models.ManyToManyField(blank=True, to='hotline.product')),
                ('status_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotline.status')),
                ('technician_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotline.technician')),
            ],
        ),
    ]
