# Generated by Django 3.2.6 on 2021-11-11 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotline', '0002_ticket_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priority',
            name='color',
            field=models.CharField(choices=[('red', 'red'), ('orange', 'orange'), ('yellow', 'yellow'), ('green', 'green')], default='green', max_length=50),
        ),
    ]
