# Generated by Django 3.2.6 on 2021-11-11 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotline', '0004_alter_status_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='order_number',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='hotline.priority'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='hotline.status'),
        ),
    ]
