# Generated by Django 3.2.6 on 2021-11-11 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotline', '0005_auto_20211111_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='order_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
