# Generated by Django 3.2.6 on 2021-11-16 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotline', '0006_alter_ticket_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='technician',
            name='office_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
