# Generated by Django 3.2.6 on 2021-11-16 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotline', '0007_auto_20211116_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
