# Generated by Django 3.2.6 on 2021-11-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotline', '0008_technician_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='reference_email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='reference_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
