# Generated by Django 3.2.6 on 2021-11-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotline', '0009_auto_20211116_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
