# Generated by Django 3.2.9 on 2021-12-23 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotline', '0014_alter_priority_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priority',
            name='color',
            field=models.CharField(choices=[('red', 'Red'), ('orange', 'Orange'), ('yellow', 'Yellow'), ('green', 'Green')], default='green', max_length=50),
        ),
        migrations.AlterField(
            model_name='status',
            name='color',
            field=models.CharField(choices=[('bg-danger', 'bg-danger'), ('orange', 'bg-warning'), ('white', 'bg-light'), ('green', 'bg-success')], default='red', max_length=50),
        ),
    ]
