# Generated by Django 3.2.9 on 2021-12-23 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotline', '0015_auto_20211223_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='color',
            field=models.CharField(choices=[('bg-danger', 'open'), ('bg-warning', 'work in progress'), ('bg-light', 'almost there'), ('bg-success', 'closed')], default='red', max_length=50),
        ),
    ]
