# Generated by Django 3.2.9 on 2021-12-23 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotline', '0016_alter_status_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='color',
            field=models.CharField(choices=[('bg-danger', 'red'), ('bg-warning', 'orange'), ('bg-light', 'white'), ('bg-success', 'green')], default='red', max_length=50),
        ),
    ]
