# Generated by Django 3.2.9 on 2021-12-30 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotline', '0020_auto_20211230_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('1', 'low'), ('2', 'medium'), ('3', 'high'), ('4', 'urgent')], default='low', max_length=10),
        ),
    ]
