# Generated by Django 3.2.9 on 2021-12-30 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotline', '0021_alter_ticket_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(blank=True, choices=[('1', 'low'), ('2', 'medium'), ('3', 'high'), ('4', 'urgent')], default='low', max_length=10, null=True),
        ),
    ]
