# Generated by Django 3.2.9 on 2022-01-09 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotline', '0023_alter_status_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='color',
            field=models.CharField(choices=[('#7b002c', 'red'), ('orange', 'orange'), ('grey', 'grey'), ('green', 'green')], default='red', max_length=50),
        ),
    ]
