# Generated by Django 3.2.9 on 2022-01-09 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotline', '0024_alter_status_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='color',
            field=models.CharField(choices=[('#900603', 'red'), ('#d4af37', 'orange'), ('#808080', 'grey'), ('#028A0F', 'green')], default='red', max_length=50),
        ),
    ]
