# https://github.com/actions/starter-workflows/blob/main/ci/docker-image.yml

name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: self-hosted

    steps:

    # Checkout the repo
    - uses: actions/checkout@v2

    # Tests?

    # Update version and save it in variable
    # - name: Update version
    #   id: update-version
    #   run: |
    #     chmod +x "${GITHUB_WORKSPACE}/.github/update-version.sh"
    #     "${GITHUB_WORKSPACE}/.github/update-version.sh"
    #     echo "::set-output name=new_version::$(cat ${GITHUB_WORKSPACE}/core/__init__.py | grep '__version__ = ' | cut -d"'" -f2)"

    # Get current date to use in the docker image tag
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y%m%d-%H%M')"

    # Remove the older versions of the image
    - name: Find older images
      id: clean-images
      run: |
        chmod +x "${GITHUB_WORKSPACE}/.github/clean-images.sh"
        "${GITHUB_WORKSPACE}/.github/clean-images.sh"

    # Build the latest docker image
    - name: Build the Docker image
      run: docker build . --tag hotline

    # Push the image to the registry
    - name: Push to Canister registry
      run: |
        docker logout
        docker tag hotline sannae/hotline:${{ steps.date.outputs.date }}
        docker tag hotline sannae/hotline:latest
        docker login cloud.canister.io:5000 --username=${{ secrets.CANISTER_ID }} --password=${{ secrets.CANISTER_PASSWORD }}
        # docker push sannae/hotline:latest
        docker push

    # Remove the local image

    # Publish to Azure App Services
