# https://github.com/actions/starter-workflows/blob/main/ci/docker-image.yml

name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: self-hosted

    steps:

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --tag hotline:${{ steps.date.outputs.date }}
